---
- name: Install Apache Tomcat on Ubuntu 18.04
  hosts: appserver:&ubuntu:!centos
  become: yes
  become_method: sudo
  vars_files:
    - ./vars/vars.yml
  tasks:
    - name: Step 1 — update ubuntu packages
      apt:
        upgrade: yes
        update_cache: yes
        
    - name: Step 2 — Install Java on ubuntu 18.04
      apt:
        name: default-jdk
        state: present

    - name: Step 3 — Create Tomcat Group
      group:
        name: tomcat
        state: present
    
    - name: Step 4 — Create Tomcat User in Ubuntu
      user:
        name: tomcat
        group: tomcat
        home: /opt/tomcat
        shell: /bin/false
        createhome: yes

    - name: Step 5 - extract the archive to /opt/tomcat directory (Downloading and installing) in ubuntu
      unarchive:
        src: "{{tomcat_source.ubuntu}}"
        dest: "{{tomcat_destination}}"
        remote_src: yes
        extra_opts: [--strip-components=1]
        creates: "{{tomcat_path.ubuntu}}"
      notify:
        - Step 6 - Update permissions (Give the tomcat group ownership over the entire installation directory)
        - Step 7 give the tomcat group read access to the conf directory and all of its contents
        - Step 8 give the tomcat group execute access to the directory itself
        - Step 9 Make the tomcat user the owner of the webapps, work, temp, and logs directories


    - name: Step 10 Create a systemd Service File
      template:
        src: ./ubuntu/tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
      notify:
        - Step 11 Reload the systemd daemon


  handlers:
    - name: Step 11 Reload the systemd daemon
      systemd:
        name: tomcat
        state: started
        enabled: true
        daemon_reload: yes

    - name: Step 6 - Update permissions (Give the tomcat group ownership over the entire installation directory)
      file:
        path: /opt/tomcat
        state: directory
        recurse: yes
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"

    - name: Step 7 give the tomcat group read access to the conf directory and all of its contents
      file:
        path: /conf
        state: directory
        recurse: yes
        owner: tomcat
        group: tomcat
        mode: "g=r"

    - name: Step 8 give the tomcat group execute access to the directory itself
      file:
        path: /conf
        state: directory
        recurse: no
        owner: tomcat
        group: tomcat
        mode: "g=x"
    
    - name: Step 9 Make the tomcat user the owner of the webapps, work, temp, and logs directories
      file:
        path:
          - webapps/
          - work/
          - temp/
          - logs/
        state: directory
        owner: tomcat
        group: tomcat
        recurse: yes
    

- name: Install Apache Tomcat on Centos7
  hosts: appserver:&centos:!ubuntu
  become: yes
  become_method: sudo
  vars_files:
    - ./vars/vars.yml
  tasks:
    - name: Step 1 — update centos packages
      yum:
        update_cache: yes
        
    - name: Step 2 — Install Java on centos7
      yum:
        name: java-1.7.0-openjdk-devel
        state: present

    - name: Step 3 — Create Tomcat Group
      group:
        name: tomcat
        state: present
    
    - name: Step 4 — Create Tomcat User
      user:
        name: tomcat
        group: tomcat
        home: /opt/tomcat
        shell: /bin/nologin
        createhome: yes

    - name: Step 5 - extract the archive to /opt/tomcat directory (Downloading and installing) in Centos7
      unarchive:
        src: "{{tomcat_source.centos}}"
        dest: "{{tomcat_destination}}"
        remote_src: yes
        extra_opts: [--strip-components=1]
        creates: "{{tomcat_path.centos}}"
      notify:
        - Step 6 - Update permissions (Give the tomcat group ownership over the entire installation directory)
        - Step 7 give the tomcat group read access to the conf directory and all of its contents
        - Step 8 give the tomcat group execute access to the directory itself
        - Step 9 Make the tomcat user the owner of the webapps, work, temp, and logs directories 


    - name: Step 10 Create a systemd Service File
      template:
        src: ./centos/tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
      notify:
        - Step 11 Reload the systemd daemon



  handlers:
    - name: Step 6 - Update permissions (Give the tomcat group ownership over the entire installation directory)
      file:
        path: /opt/tomcat
        state: directory
        recurse: yes
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"

    - name: Step 7 give the tomcat group read access to the conf directory and all of its contents
      file:
        path: /conf
        state: directory
        recurse: yes
        owner: tomcat
        group: tomcat
        mode: "g=r"

    - name: Step 8 give the tomcat group execute access to the directory itself
      file:
        path: /conf
        state: directory
        recurse: no
        owner: tomcat
        group: tomcat
        mode: "g=x"
    
    - name: Step 9 Make the tomcat user the owner of the webapps, work, temp, and logs directories
      file:
        path:
          - webapps/
          - work/
          - temp/
          - logs/
        state: directory
        owner: tomcat
        group: tomcat
        recurse: yes

    - name: Step 11 Reload the systemd daemon
      systemd:
        name: tomcat
        state: started
        enabled: true
        daemon_reload: yes