---
- name: Install Apache Tomcat on Ubuntu 18.04 and Centos7
  hosts: appserver:&ubuntu:!centos
  become: yes
  become_method: sudo
  vars_files:
    - ./vars/vars.yml
  tasks:
    - name: Step 1 — update ubuntu packages
      apt: update_cache=yes name=tar state=present

    - name: Step 2 — Install Java on ubuntu 18.04
      apt: name=default-jdk state=present update_cache=yes

    - name: Step 3 — Create Tomcat Group
      group: name=tomcat state=present
    
    - name: Step 4 — Create Tomcat User in Ubuntu
      user: name=tomcat group=tomcat home=/opt/tomcat shell=/bin/false createhome=yes

    - name: Step 5 - extract the archive to /opt/tomcat directory (Downloading and installing) in ubuntu
      unarchive: src="{{tomcat_source.ubuntu}}" dest="{{tomcat_destination.ubuntu}}" remote_src=yes

    - name: Step 6 - Update permissions (Give the tomcat group ownership over the entire installation directory)
      file: path=/opt/tomcat state=directory recurse=yes owner=tomcat group=tomcat mode="u+rwx,g+rx,o=rx"

    - name: Step 7 give the tomcat group read access to the conf directory and all of its contents
      file: path=/conf state=directory recurse=yes owner=tomcat group=tomcat mode="g=r"

    - name: Step 8 give the tomcat group execute access to the directory itself
      file: path=/conf state=directory recurse=no owner=tomcat group=tomcat mode="g=x"
    
    - name: Step 9 Make the tomcat user the owner of the webapps, work, temp, and logs directories
      file:
        path:
          - webapps/
          - work/
          - temp/
          - logs/
        state: directory
        owner: tomcat
        group: tomcat
        recurse: yes

    - name: Step 10 Create a systemd Service File
      copy: src=tomcat.service dest=/etc/systemd/system/

    - name: Step 11 Reload the systemd daemon
      systemd: name=tomcat state=started enabled=true daemon_reload=yes