- name: Install Apache Tomcat on Ubuntu 18.04 and Centos7
  hosts: ubuntu
  become: yes
  tasks:
    - name: Step 1 — Install Java
      package: name=default-jdk state=present
    
    - name: Step 2 — Create Tomcat Group
      group: name=tomcat state=present
    
    - name: Step 3 — Create Tomcat User
      user: name=tomcat group=tomcat home="/opt/tomcat" shell="/bin/false"
    
    - name: Step 4 — Download Tomcat tar file
      get_url: url="https://downloads.apache.org/tomcat/tomcat-9/v9.0.41/bin/apache-tomcat-9.0.41.tar.gz" dest="/tmp/apache-tomcat-9.0.41.tar.gz"
    
    - name: Step 5 - extract the archive to /opt/tomcat directory
      archive: src="/tmp/apache-tomcat-9.0.41.tar.gz" dest="/opt/tomcat"

    - name: Step 6 - Update permissions (Give the tomcat group ownership over the entire installation directory)
      file: path="/opt/tomcat" state=directory recurse=yes owner=tomcat group=tomcat