---
- name: Install Apache Tomcat on Ubuntu 18.04 and Centos7
  hosts: appserver
  become: yes
  tasks:
    - name: Step 1 — Install Java on Ubuntu
      apt: name=default-jdk state=present update_cache=yes
      when: ansible_os_family == "Debian"

    - name: Step 1 — Install Java on centos7
      yum: name=java-1.7.0-openjdk-devel state=present update_cache=yes
      when: ansible_os_family == "RedHat"

    - name: Step 2 — Create Tomcat Group
      group: name=tomcat state=present
    
    - name: Step 3 — Create Tomcat User in Ubuntu
      user: name=tomcat group=tomcat home="/opt/tomcat" shell="/bin/false"
      when: ansible_os_family == "Debian"

    - name: Step 3 — Create Tomcat User in Centos7
      user: name=tomcat group=tomcat home="/opt/tomcat" shell="/bin/nologin"
      when: ansible_os_family == "RedHat"
    
    - name: Step 4 - extract the archive to /opt/tomcat directory (Downloading and installing) in ubuntu
      unarchive: src=https://downloads.apache.org/tomcat/tomcat-9/v9.0.41/bin/apache-tomcat-9.0.41.tar.gz dest=/opt/tomcat remote_src=yes
      when: ansible_os_family == "Debian"

    - name: Step 4 - extract the archive to /opt/tomcat directory (Downloading and installing) in centos7
      unarchive: src=https://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.37/bin/apache-tomcat-8.5.37.tar.gz dest=/opt/tomcat remote_src=yes
      when: ansible_os_family == "RedHat"

    - name: Step 5 - Update permissions (Give the tomcat group ownership over the entire installation directory)
      file: path=/opt/tomcat state=directory recurse=yes owner=tomcat group=tomcat

    - name: Step 7 give the tomcat group read access to the conf directory and all of its contents, and execute access to the directory itself
      file: path=/conf state=directory recurse=yes owner=tomcat group=tomcat mode=g=rx
    
    - name: Step 8 Make the tomcat user the owner of the webapps, work, temp, and logs directories
      file:
        path:
          - webapps/
          - work/
          - temp/
          - logs/
        state: directory
        owner: tomcat
        group: tomcat