---
- name: Install Apache Tomcat on Ubuntu 18.04 and Centos7
  hosts: appserver
  become: yes
  tasks:
    - name: Step 1 — Install Java
      apt:
        name: default-jdk
        update_cache: yes
        state: present
      when: ansible_facts['os_family'] == "Debian"