---
- name: install lamp stack
  hosts: webserver
  become: yes
  tasks:
    - name: Step One — Removing info.php
      file:
        path: /var/www/html/info.php
        state: absent

    - name: Step Two — Uninstall PHP
      package: name="{{php_package}}" state=absent

    - name: Step Three — Uninstall MySQL (MariaDB)
      package: name="{{mysql_package}}" state=absent

    - name: Step Four — Uninstall Apache
      package: name="{{apache_package}}" state=absent